# Generated by Django 5.2.7 on 2025-11-23 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('contractor', 'پیمانکار'), ('project_manager', 'مدیر طرح'), ('employer', 'کارفرما'), ('admin', 'ادمین'), ('supervisor', 'ناظر'), ('engineer', 'مهندس')], max_length=20, unique=True, verbose_name='نام نقش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات نقش')),
                ('can_edit_measurements', models.BooleanField(default=False, verbose_name='می\u200cتواند متره را ویرایش کند')),
                ('can_approve', models.BooleanField(default=False, verbose_name='می\u200cتواند تأیید کند')),
                ('can_view_financial', models.BooleanField(default=False, verbose_name='می\u200cتواند اطلاعات مالی را ببیند')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نقش کاربر',
                'verbose_name_plural': 'نقش\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت/سازمان')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='سمت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='آواتار')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('contractor', 'پیمانکار'), ('project_manager', 'مدیر طرح'), ('employer', 'کارفرما'), ('supervisor', 'ناظر'), ('consultant', 'مشاور')], max_length=20, verbose_name='نقش در پروژه')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع مسئولیت')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان مسئولیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_users', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص\u200cدهنده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='project.project', verbose_name='پروژه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر پروژه',
                'verbose_name_plural': 'کاربران پروژه',
                'ordering': ['-is_primary', 'role'],
                'unique_together': {('project', 'user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('contractor', 'پیمانکار'), ('project_manager', 'مدیر طرح'), ('employer', 'کارفرما'), ('admin', 'ادمین'), ('supervisor', 'ناظر'), ('engineer', 'مهندس')], max_length=20, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقش کاربر',
                'verbose_name_plural': 'نقش\u200cهای کاربران',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
