# Generated by Django 5.2.7 on 2025-11-26 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('role', models.CharField(choices=[('contractor', 'پیمانکار'), ('project_manager', 'مدیر طرح'), ('employer', 'کارفرما'), ('admin', 'ادمین'), ('supervisor', 'ناظر'), ('engineer', 'مهندس')], max_length=20, verbose_name='نقش')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='توکن')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شده'), ('expired', 'منقضی شده')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه کاربر',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cهای کاربران',
            },
        ),
    ]
