# Generated by Django 5.2.7 on 2025-11-26 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fehrestbaha', '0002_alter_historicalpricelist_options_and_more'),
        ('sooratvaziat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedmeasurement',
            name='price_list_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_measurements', to='fehrestbaha.pricelistitem', verbose_name='آیتم فهرست بها'),
        ),
    ]
