# Generated by Django 5.2.7 on 2025-11-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sooratvaziat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeasurementsession',
            name='discipline_choice',
            field=models.CharField(blank=True, choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], max_length=2, null=True, verbose_name='رشته (ابنیه، مکانیک، etc)'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='discipline_choice',
            field=models.CharField(blank=True, choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], max_length=2, null=True, verbose_name='رشته (ابنیه، مکانیک، etc)'),
        ),
    ]
