# Generated by Django 5.2.7 on 2025-11-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sooratvaziat', '0002_historicalmeasurementsession_discipline_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeasurementsession',
            name='session_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ صورت جلسه'),
        ),
        migrations.AddField(
            model_name='measurementsession',
            name='session_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ صورت جلسه'),
        ),
    ]
