# Generated by Django 5.2.7 on 2025-11-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sooratvaziat', '0003_historicalmeasurementsession_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeasurementsession',
            name='session_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ صورت جلسه'),
        ),
        migrations.AlterField(
            model_name='measurementsession',
            name='session_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ صورت جلسه'),
        ),
    ]
