# Generated by Django 5.2.7 on 2025-11-23 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('model_app_label', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.TextField(max_length=200)),
                ('changed_data', models.JSONField(blank=True, default=dict, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'model_app_label', 'model_name'], name='ProjectLog__created_ec39c8_idx'), models.Index(fields=['user', 'action'], name='ProjectLog__user_id_41c86b_idx'), models.Index(fields=['content_type', 'object_id'], name='ProjectLog__content_ce47dd_idx')],
            },
        ),
    ]
