# Generated by Django 5.2.7 on 2025-11-23 15:00

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_name', models.CharField(help_text='نام کامل و دقیق پروژه', max_length=255, verbose_name='نام پروژه')),
                ('project_code', models.CharField(db_index=True, help_text='کد منحصر به فرد پروژه - قابل تغییر نیست', max_length=50, verbose_name='کد پروژه')),
                ('employer', models.CharField(help_text='نام کامل کارفرما یا سازمان کارفرما', max_length=255, verbose_name='کارفرما')),
                ('contractor', models.CharField(help_text='نام کامل پیمانکار مجری پروژه', max_length=255, verbose_name='پیمانکار')),
                ('consultant', models.CharField(blank=True, help_text='نام مدیر طرح، مشاور یا شرکت مشاور', max_length=255, null=True, verbose_name='مدیر طرح یا مشاور')),
                ('supervising_engineer', models.CharField(blank=True, help_text='نام مهندس ناظر پروژه', max_length=255, null=True, verbose_name='مهندس ناظر')),
                ('city', models.CharField(help_text='شهر محل اجرای پروژه', max_length=100, verbose_name='شهر پروژه')),
                ('province', models.CharField(help_text='استان محل پروژه', max_length=100, verbose_name='استان')),
                ('country', models.CharField(default='ایران', help_text='کشور محل پروژه', max_length=100, verbose_name='کشور')),
                ('contract_number', models.CharField(help_text='شماره رسمی قرارداد', max_length=50, verbose_name='شماره قرارداد')),
                ('contract_date', models.DateField(help_text='تاریخ انعقاد قرارداد', verbose_name='تاریخ قرارداد')),
                ('execution_year', models.IntegerField(help_text='سال شروع اجرای پروژه یا صدور صورت وضعیت', validators=[django.core.validators.MinValueValidator(1370), django.core.validators.MaxValueValidator(1410)], verbose_name='سال اجرا بر اساس صورت وضعیت')),
                ('contract_amount', models.DecimalField(decimal_places=0, help_text='مبلغ کل قرارداد به ریال', max_digits=15, validators=[django.core.validators.MinValueValidator(100000)], verbose_name='مبلغ قرارداد')),
                ('project_type', models.CharField(choices=[('civil', 'عمرانی'), ('building', 'ساختمانی'), ('bridge', 'پل\u200cسازی'), ('dam', 'سدسازی'), ('road', 'جاده\u200cسازی'), ('electrical', 'برقی'), ('mechanical', 'مکانیکی'), ('other', 'سایر')], default='civil', help_text='دسته\u200cبندی نوع پروژه', max_length=20, verbose_name='نوع پروژه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('in_progress', 'در حال اجرا'), ('under_review', 'در حال بررسی'), ('awaiting_approval', 'منتظر تأیید'), ('completed', 'تمام\u200cشده'), ('suspended', 'معلق'), ('cancelled', 'لغو شده')], default='active', help_text='وضعیت فعلی پروژه', max_length=20, verbose_name='وضعیت پروژه')),
                ('contract_file', models.TextField(blank=True, help_text='فایل PDF یا Word قرارداد', max_length=100, null=True, verbose_name='فایل قرارداد')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ آخرین صورت وضعیت (اختیاری)', max_digits=21, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ صورت وضعیت')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره پروژه', null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان ایجاد')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='کاربری که این پروژه را ایجاد کرده است', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='کاربر آخر ویرایش\u200cکننده', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'historical پروژه عمرانی',
                'verbose_name_plural': 'historical پروژه\u200cهای عمرانی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='نام کامل و دقیق پروژه', max_length=255, verbose_name='نام پروژه')),
                ('project_code', models.CharField(help_text='کد منحصر به فرد پروژه - قابل تغییر نیست', max_length=50, unique=True, verbose_name='کد پروژه')),
                ('employer', models.CharField(help_text='نام کامل کارفرما یا سازمان کارفرما', max_length=255, verbose_name='کارفرما')),
                ('contractor', models.CharField(help_text='نام کامل پیمانکار مجری پروژه', max_length=255, verbose_name='پیمانکار')),
                ('consultant', models.CharField(blank=True, help_text='نام مدیر طرح، مشاور یا شرکت مشاور', max_length=255, null=True, verbose_name='مدیر طرح یا مشاور')),
                ('supervising_engineer', models.CharField(blank=True, help_text='نام مهندس ناظر پروژه', max_length=255, null=True, verbose_name='مهندس ناظر')),
                ('city', models.CharField(help_text='شهر محل اجرای پروژه', max_length=100, verbose_name='شهر پروژه')),
                ('province', models.CharField(help_text='استان محل پروژه', max_length=100, verbose_name='استان')),
                ('country', models.CharField(default='ایران', help_text='کشور محل پروژه', max_length=100, verbose_name='کشور')),
                ('contract_number', models.CharField(help_text='شماره رسمی قرارداد', max_length=50, verbose_name='شماره قرارداد')),
                ('contract_date', models.DateField(help_text='تاریخ انعقاد قرارداد', verbose_name='تاریخ قرارداد')),
                ('execution_year', models.IntegerField(help_text='سال شروع اجرای پروژه یا صدور صورت وضعیت', validators=[django.core.validators.MinValueValidator(1370), django.core.validators.MaxValueValidator(1410)], verbose_name='سال اجرا بر اساس صورت وضعیت')),
                ('contract_amount', models.DecimalField(decimal_places=0, help_text='مبلغ کل قرارداد به ریال', max_digits=15, validators=[django.core.validators.MinValueValidator(100000)], verbose_name='مبلغ قرارداد')),
                ('project_type', models.CharField(choices=[('civil', 'عمرانی'), ('building', 'ساختمانی'), ('bridge', 'پل\u200cسازی'), ('dam', 'سدسازی'), ('road', 'جاده\u200cسازی'), ('electrical', 'برقی'), ('mechanical', 'مکانیکی'), ('other', 'سایر')], default='civil', help_text='دسته\u200cبندی نوع پروژه', max_length=20, verbose_name='نوع پروژه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('in_progress', 'در حال اجرا'), ('under_review', 'در حال بررسی'), ('awaiting_approval', 'منتظر تأیید'), ('completed', 'تمام\u200cشده'), ('suspended', 'معلق'), ('cancelled', 'لغو شده')], default='active', help_text='وضعیت فعلی پروژه', max_length=20, verbose_name='وضعیت پروژه')),
                ('contract_file', models.FileField(blank=True, help_text='فایل PDF یا Word قرارداد', null=True, upload_to='contracts/%Y/%m/', verbose_name='فایل قرارداد')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='مبلغ آخرین صورت وضعیت (اختیاری)', max_digits=21, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ صورت وضعیت')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره پروژه', null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='برای حذف نرم: غیرفعال = مخفی از لیست\u200cها', verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حذف')),
                ('created_by', models.ForeignKey(help_text='کاربری که این پروژه را ایجاد کرده است', on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('modified_by', models.ForeignKey(blank=True, help_text='کاربر آخر ویرایش\u200cکننده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_projects', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'پروژه عمرانی',
                'verbose_name_plural': 'پروژه\u200cهای عمرانی',
                'ordering': ['-created_at', 'project_name'],
                'permissions': [('can_assign_roles', 'Can assign roles to projects'), ('can_manage_all_projects', 'Can manage all projects'), ('can_view_all_projects', 'Can view all projects')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStatusReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], help_text='رشته تخصصی صورت وضعیت', max_length=2, verbose_name='رشته')),
                ('report_number', models.PositiveIntegerField(help_text='شماره ترتیبی صورت وضعیت', verbose_name='شماره صورت وضعیت')),
                ('issue_date', models.DateField(help_text='تاریخ صدور صورت وضعیت', verbose_name='تاریخ صدور')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مبلغ این صورت وضعیت به ریال', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ صورت وضعیت')),
                ('progress_percentage', models.DecimalField(decimal_places=2, help_text='درصد پیشرفت فیزیکی تا این صورت وضعیت', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت')),
                ('attachment', models.TextField(blank=True, help_text='فایل PDF صورت وضعیت', max_length=100, null=True, verbose_name='فایل پیوست')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره صورت وضعیت', null=True, verbose_name='توضیحات')),
                ('approval_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت تأیید')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.project', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'historical صورت وضعیت',
                'verbose_name_plural': 'historical صورت وضعیت\u200cها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], help_text='رشته تخصصی صورت وضعیت', max_length=2, verbose_name='رشته')),
                ('report_number', models.PositiveIntegerField(help_text='شماره ترتیبی صورت وضعیت', verbose_name='شماره صورت وضعیت')),
                ('issue_date', models.DateField(help_text='تاریخ صدور صورت وضعیت', verbose_name='تاریخ صدور')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مبلغ این صورت وضعیت به ریال', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ صورت وضعیت')),
                ('progress_percentage', models.DecimalField(decimal_places=2, help_text='درصد پیشرفت فیزیکی تا این صورت وضعیت', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد پیشرفت')),
                ('attachment', models.FileField(blank=True, help_text='فایل PDF صورت وضعیت', null=True, upload_to='status_reports/%Y/%m/', verbose_name='فایل پیوست')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره صورت وضعیت', null=True, verbose_name='توضیحات')),
                ('approval_status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20, verbose_name='وضعیت تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='project.project', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'صورت وضعیت',
                'verbose_name_plural': 'صورت وضعیت\u200cها',
                'ordering': ['-issue_date', 'report_number'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code', 'is_active'], name='project_pro_project_67818f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_active'], name='project_pro_status_aaf5bb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['execution_year', 'is_active'], name='project_pro_executi_53ee15_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['city', 'province', 'is_active'], name='project_pro_city_20e465_idx'),
        ),
        migrations.AddIndex(
            model_name='statusreport',
            index=models.Index(fields=['project', 'discipline', 'is_active'], name='project_sta_project_4e0484_idx'),
        ),
        migrations.AddIndex(
            model_name='statusreport',
            index=models.Index(fields=['issue_date', 'is_active'], name='project_sta_issue_d_932c7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='statusreport',
            unique_together={('project', 'report_number', 'discipline')},
        ),
    ]
