# Generated by Django 5.2.7 on 2025-11-08 15:15

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('project_code', models.CharField(db_index=True, max_length=50, verbose_name='کد پروژه')),
                ('employer', models.CharField(max_length=255, verbose_name='کارفرما')),
                ('contractor', models.CharField(max_length=255, verbose_name='پیمانکار')),
                ('consultant', models.CharField(blank=True, max_length=255, null=True, verbose_name='مدیر طرح یا مشاور')),
                ('supervising_engineer', models.CharField(blank=True, max_length=255, null=True, verbose_name='مهندس ناظر')),
                ('city', models.CharField(max_length=100, verbose_name='شهر پروژه')),
                ('province', models.CharField(max_length=100, verbose_name='استان پروژه')),
                ('country', models.CharField(default='ایران', max_length=100, verbose_name='کشور پروژه')),
                ('contract_number', models.CharField(max_length=50, verbose_name='شماره قرارداد')),
                ('contract_date', models.DateField(verbose_name='تاریخ قرارداد')),
                ('execution_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1370)], verbose_name='سال اجرا بر اساس صورت وضعیت')),
                ('contract_amount', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ قرارداد')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تمام\u200cشده')], default='active', max_length=50, verbose_name='وضعیت پروژه')),
                ('contract_file', models.TextField(blank=True, max_length=100, null=True, verbose_name='فایل قرارداد')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ صورت وضعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال (برای حذف نرم)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'historical پروژه عمرانی',
                'verbose_name_plural': 'historical پروژه\u200cهای عمرانی',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('project_code', models.CharField(max_length=50, unique=True, verbose_name='کد پروژه')),
                ('employer', models.CharField(max_length=255, verbose_name='کارفرما')),
                ('contractor', models.CharField(max_length=255, verbose_name='پیمانکار')),
                ('consultant', models.CharField(blank=True, max_length=255, null=True, verbose_name='مدیر طرح یا مشاور')),
                ('supervising_engineer', models.CharField(blank=True, max_length=255, null=True, verbose_name='مهندس ناظر')),
                ('city', models.CharField(max_length=100, verbose_name='شهر پروژه')),
                ('province', models.CharField(max_length=100, verbose_name='استان پروژه')),
                ('country', models.CharField(default='ایران', max_length=100, verbose_name='کشور پروژه')),
                ('contract_number', models.CharField(max_length=50, verbose_name='شماره قرارداد')),
                ('contract_date', models.DateField(verbose_name='تاریخ قرارداد')),
                ('execution_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1370)], verbose_name='سال اجرا بر اساس صورت وضعیت')),
                ('contract_amount', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ قرارداد')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('completed', 'تمام\u200cشده')], default='active', max_length=50, verbose_name='وضعیت پروژه')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='فایل قرارداد')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ صورت وضعیت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال (برای حذف نرم)')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'پروژه عمرانی',
                'verbose_name_plural': 'پروژه\u200cهای عمرانی',
                'ordering': ['-contract_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalStatusReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], max_length=2, verbose_name='رشته (ابنیه، مکانیک، etc)')),
                ('attachment', models.TextField(blank=True, max_length=100, null=True, verbose_name='فایل پیوست (مثل PDF صورت وضعیت)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال (برای حذف نرم)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.project', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'historical صورت وضعیت',
                'verbose_name_plural': 'historical صورت وضعیت\u200cها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], max_length=2, verbose_name='رشته (ابنیه، مکانیک، etc)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='status_reports/', verbose_name='فایل پیوست (مثل PDF صورت وضعیت)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال (برای حذف نرم)')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='project.project', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'صورت وضعیت',
                'verbose_name_plural': 'صورت وضعیت\u200cها',
                'ordering': ['-created_at', 'discipline'],
            },
        ),
    ]
