# Generated by Django 5.2.7 on 2025-11-26 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='درصد مالیات بر ارزش افزوده (مثال: 10)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات بر ارزش افزوده'),
        ),
        migrations.AddField(
            model_name='project',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='درصد مالیات بر ارزش افزوده (مثال: 10)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات بر ارزش افزوده'),
        ),
    ]
