# Generated by Django 5.2.7 on 2025-11-08 15:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPriceList',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('discipline_choice', models.CharField(choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], max_length=2, verbose_name='رشته (ابنیه، مکانیک، etc)')),
                ('discipline', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال (برای حذف نرم)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'historical price list',
                'verbose_name_plural': 'historical price lists',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_choice', models.CharField(choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], max_length=2, verbose_name='رشته (ابنیه، مکانیک، etc)')),
                ('discipline', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال (برای حذف نرم)')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPriceListItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('row_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال (برای حذف نرم)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
                ('price_list', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fehrestbaha.pricelist')),
            ],
            options={
                'verbose_name': 'historical price list item',
                'verbose_name_plural': 'historical price list items',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('is_starred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال (برای حذف نرم)')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ویرایش\u200cکننده')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fehrestbaha.pricelist')),
            ],
        ),
    ]
