# Generated by Django 5.2.7 on 2025-11-26 10:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fehrestbaha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpricelist',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical فهرست بها', 'verbose_name_plural': 'historical فهرست\u200cهای بها'},
        ),
        migrations.AlterModelOptions(
            name='historicalpricelistitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical آیتم فهرست بها', 'verbose_name_plural': 'historical آیتم\u200cهای فهرست بها'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['-year', 'discipline_choice', 'discipline'], 'verbose_name': 'فهرست بها', 'verbose_name_plural': 'فهرست\u200cهای بها'},
        ),
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['row_number', 'description'], 'verbose_name': 'آیتم فهرست بها', 'verbose_name_plural': 'آیتم\u200cهای فهرست بها'},
        ),
        migrations.AlterField(
            model_name='historicalpricelist',
            name='discipline',
            field=models.CharField(help_text='مثلاً: ابنیه ۱۴۰۲، مکانیک ۱۴۰۰', max_length=100, verbose_name='نسخه فهرست بها'),
        ),
        migrations.AlterField(
            model_name='historicalpricelist',
            name='discipline_choice',
            field=models.CharField(choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], max_length=2, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='historicalpricelist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='historicalpricelist',
            name='year',
            field=models.IntegerField(blank=True, help_text='سال انتشار فهرست بها', null=True, verbose_name='سال فهرست بها'),
        ),
        migrations.AlterField(
            model_name='historicalpricelistitem',
            name='description',
            field=models.TextField(help_text='شرح کامل آیتم فهرست بها', verbose_name='شرح آیتم'),
        ),
        migrations.AlterField(
            model_name='historicalpricelistitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='historicalpricelistitem',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='آیتم\u200cهای مهم و پرکاربرد', verbose_name='ستاره\u200cدار'),
        ),
        migrations.AlterField(
            model_name='historicalpricelistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='قیمت واحد به ریال', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='historicalpricelistitem',
            name='price_list',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fehrestbaha.pricelist', verbose_name='فهرست بها مرتبط'),
        ),
        migrations.AlterField(
            model_name='historicalpricelistitem',
            name='row_number',
            field=models.CharField(help_text='شماره ردیف در فهرست بها (مثال: ۱۸۰۲۰۳)', max_length=10, verbose_name='شماره ردیف'),
        ),
        migrations.AlterField(
            model_name='historicalpricelistitem',
            name='unit',
            field=models.CharField(help_text='واحد اندازه\u200cگیری (مثال: متر مربع، متر مکعب)', max_length=50, verbose_name='واحد اندازه\u200cگیری'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='discipline',
            field=models.CharField(help_text='مثلاً: ابنیه ۱۴۰۲، مکانیک ۱۴۰۰', max_length=100, verbose_name='نسخه فهرست بها'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='discipline_choice',
            field=models.CharField(choices=[('AB', 'ابنیه'), ('ME', 'مکانیک'), ('EL', 'برق'), ('OT', 'سایر')], max_length=2, verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='year',
            field=models.IntegerField(blank=True, help_text='سال انتشار فهرست بها', null=True, verbose_name='سال فهرست بها'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='description',
            field=models.TextField(help_text='شرح کامل آیتم فهرست بها', verbose_name='شرح آیتم'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='is_starred',
            field=models.BooleanField(default=False, help_text='آیتم\u200cهای مهم و پرکاربرد', verbose_name='ستاره\u200cدار'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='قیمت واحد به ریال', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fehrestbaha.pricelist', verbose_name='فهرست بها مرتبط'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='row_number',
            field=models.CharField(help_text='شماره ردیف در فهرست بها (مثال: ۱۸۰۲۰۳)', max_length=10, verbose_name='شماره ردیف'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='unit',
            field=models.CharField(help_text='واحد اندازه\u200cگیری (مثال: متر مربع، متر مکعب)', max_length=50, verbose_name='واحد اندازه\u200cگیری'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('discipline_choice', 'discipline', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('price_list', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['discipline_choice', 'is_active'], name='fehrestbaha_discipl_9cc432_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['year', 'is_active'], name='fehrestbaha_year_311024_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['row_number', 'is_active'], name='fehrestbaha_row_num_3bcf9a_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['price_list', 'is_active'], name='fehrestbaha_price_l_faee9f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['is_starred', 'is_active'], name='fehrestbaha_is_star_58f918_idx'),
        ),
    ]
